### ISSUE TITLE
Is this available for only Sublime 3? Or has this been deprecated? (not showing up in package control)

### ISSUE THREAD

**Issue by g12mcgov** [bgreenlee/SublimeHound#3]
Question is pretty self explanatory, but I was searching for it on package control in Sublime Text 2 and nothing came up.

**Comment by bgreenlee** [comment]
The name in Package Control is "Hound Search". Package Control discourages using "Sublime" in the name of the package, but not having it in the Github repo name opens up the possibily of confusion w/ the actual Hound project.

**Comment by bgreenlee** [comment]
Oh, I believe it is ST3 only. I can't remember offhand why, but I know the code to do the search results was rather gnarly and probably uses ST3 apis.
